development:
  user_name: ''
  password: ''
  integrators_key: ''
  account_id: ''
  default_endpoint_url: 'https://demo.docusign.net/api/3.0/api.asmx'
  credential_endpoint_url: 'https://demo.docusign.net/api/3.0/Credential.asmx'